version: '3.0'
services:
  gerrit:
    image: docker.io/gerritcodereview/gerrit:3.7.0-rc2
    volumes:
      - ./plugins/gerrit-oauth-provider-3.5.0.1.jar:/var/gerrit/plugins/gerrit-oauth-provider.jar
      - git-volume:/var/gerrit/git
      - index-volume:/var/gerrit/index
      - cache-volume:/var/gerrit/cache
    ports:
      - "29418:29418"
      - "8080:8080"

volumes:
  git-volume:
  index-volume:
  cache-volume:
