### Create configuration
POST http://localhost:8081/projects-source-configurations
Content-Type: application/json

{
  "systemType": "test_provider",
  "configurationId": "test",
  "properties": {}
}

### Synchronize test project
POST http://localhost:8081/projects-source-configurations/test/synchronize

{}

### List configurations
GET http://localhost:8081/projects-source-configurations/list
Accept: application/json;text/json


### List projects
GET http://localhost:8081/projects/list
Accept: application/json;text/json
