$id: DeploymentReviewEvent
$schema: https://json-schema.org/draft/2020-12/schema
type: object
description: |
  This event occurs when there is activity relating to deployment reviews. For more information, see "About deployments." For information about the APIs to manage deployments, see the GraphQL API documentation or "Deployments" in the REST API documentation.
  
  For activity relating to deployment creation or deployment status, use the deployment or deployment_status event.
  
  To subscribe to this event, a GitHub App must have at least read-level access for the "Deployments" repository permission.
properties:
  reviewers:
    type: array
    items:
      $ref: components/reviewers.yaml#
additionalProperties: false
