version: "3.9"
services:

  # https://hub.docker.com/_/postgres
  postgres:
    image: docker.io/library/postgres:16.1
    restart: "always"
    environment:
      POSTGRES_USER: "${POSTGRES_USERNAME}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DATABASE}"
      # Fixes problems with file ownership on windows bind mounts
      PGDATA: "/var/lib/postgresql/data/pgdata"
    # volumes:
    #   - "pgdata:/var/lib/postgresql/data"
    #   - ./init.sql:/docker-entrypoint-initdb.d/

  # https://hub.docker.com/r/jboss/keycloak
  keycloak:
    image: "jboss/keycloak:16.1.1"
    restart: "always"
    command:
      - "-Dkeycloak.migration.action=import"
      - "-Dkeycloak.migration.provider=dir"
      - "-Dkeycloak.migration.dir=/config/"
      - "-Dkeycloak.migration.strategy=IGNORE_EXISTING"
    volumes:
      - "./keycloak/:/config/"
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
      DB_VENDOR: postgres
      DB_PORT: 5432
      DB_USER: "${POSTGRES_USERNAME}"
      DB_PASSWORD: "${POSTGRES_PASSWORD}"
      DB_ADDR: postgres
      DB_DATABASE: "${POSTGRES_DATABASE}"
      # KEYCLOAK_STATISTICS: [all|[jgroups,db,http]
      KEYCLOAK_STATISTICS: db,http
    ports:
      - "${KEYCLOAK_WEB_PORT}:8080"
    depends_on:
      - postgres

volumes:
  pgdata: ~