version: "3.9"
services:

  # https://hub.docker.com/r/sonatype/nexus3
  nexus:
    image: docker.io/sonatype/nexus3:3.64.0
    ports:
      - "${NEXUS_WEB_PORT}:8081"
    volumes:
      - nexus-data:/nexus-data

volumes:
  nexus-data: ~