version: "3.9"
services:

  # https://hub.docker.com/r/osixia/openldap
  openldap:
    image: "docker.io/osixia/openldap:1.5.0"
    restart: "always"
    ports:
      - ":389"
      - ":636"
    command:
      - "-ldebug"
      - "--copy-service"
    environment:
      LDAP_ORGANISATION: Example
      LDAP_DOMAIN: example.org
      LDAP_ADMIN_PASSWORD: secret
      LDAP_SEED_INTERNAL_LDIF_PATH: "/home/ldif"
    volumes:
      - "./openldap/ldif/01.ldif:/home/ldif/01.ldif:ro"

  # https://hub.docker.com/r/osixia/phpldapadmin
  phpldapadmin:
    image: 'docker.io/osixia/phpldapadmin:0.9.0'
    restart: "on-failure"
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: openldap
      PHPLDAPADMIN_HTTPS: false
    depends_on:
      - openldap
    ports:
      - ':443'
      - '${PHPLDAPADMIN_WEB_PORT}:80'