version: "3.9"
services:

  # https://hub.docker.com/r/dpage/pgadmin4
  pgadmin:
    image: docker.io/dpage/pgadmin4:8.2
    restart: "on-failure"
    ports:
      - "${PGADMIN_WEB_PORT}:8080"
      - ":443"
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: secret